// mss-protoc-gen (frontend port) — proto 契約 → frontend(型/APIクライアント/CRUD UI/pages)生成。
// self-contained: buf/protoc/python 不要。manji proto の文法を直接パースする。
// 生成物ヘッダ: "// Code generated by mss-protoc-gen. DO NOT EDIT."
// 設計: ../../DESIGN.md, KB: [[contract-to-ui-codegen]] / [[selection-design-pattern]]
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const HEADER = "// Code generated by mss-protoc-gen. DO NOT EDIT.\n";
// app/ のページは「初回だけ生成する編集可能な足場」。生成後はアプリが所有し、
// 情報設計した画面に置き換えてよい(再生成では上書きしない=scaffold)。
const SCAFFOLD_HEADER = "// Scaffolded by mss-protoc-gen — 編集可(アプリ所有)。再生成では上書きされない。\n";

// ---------- proto parser ----------
const SCALAR = { string: "string", int64: "number", int32: "number", bool: "boolean", double: "number" };
const annosFrom = (lead) => {
  const out = {};
  const re = /@(\w+)(?:\s+([^\n@]+))?/g;
  let m;
  while ((m = re.exec(lead.join("\n")))) out[m[1]] = (m[2] || "").trim();
  return out;
};

function parseProto(text) {
  const lines = text.split("\n");
  const messages = [], services = [];
  let pkg = "", lead = [], i = 0;
  const takeLead = () => { const a = annosFrom(lead); lead = []; return a; };
  while (i < lines.length) {
    const line = lines[i].trim();
    if (line.startsWith("//")) { lead.push(line.slice(2)); i++; continue; }
    if (line === "") { lead = []; i++; continue; }
    if (line.startsWith("package ")) { pkg = line.slice(8).replace(";", "").trim(); lead = []; i++; continue; }
    if (/^(syntax|option|import)\b/.test(line)) { lead = []; i++; continue; }
    let m;
    const oneLineEmpty = /\{\s*\}\s*$/.test(line);
    if ((m = line.match(/^message\s+(\w+)\s*\{/))) {
      const annotations = takeLead();
      if (oneLineEmpty) { messages.push({ name: m[1], annotations, fields: [] }); i++; continue; }
      const r = parseBlock(lines, i + 1, "field");
      messages.push({ name: m[1], annotations, fields: r.items });
      i = r.next; continue;
    }
    if ((m = line.match(/^enum\s+(\w+)\s*\{/))) {
      lead = []; i = oneLineEmpty ? i + 1 : parseBlock(lines, i + 1, "skip").next; continue;
    }
    if ((m = line.match(/^service\s+(\w+)\s*\{/))) {
      takeLead();
      if (oneLineEmpty) { services.push({ name: m[1], rpcs: [] }); i++; continue; }
      const r = parseBlock(lines, i + 1, "rpc");
      services.push({ name: m[1], rpcs: r.items });
      i = r.next; continue;
    }
    lead = []; i++;
  }
  return { package: pkg, messages, services };
}

function parseBlock(lines, start, kind) {
  const items = []; let lead = [], i = start;
  for (; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line === "}") return { items, next: i + 1 };
    if (line.startsWith("//")) { lead.push(line.slice(2)); continue; }
    if (line === "") { lead = []; continue; }
    if (kind === "field") {
      const m = line.match(/^(?:(repeated|optional)\s+)?([\w.]+)\s+(\w+)\s*=\s*\d+\s*;/);
      if (m) items.push({ name: m[3], type: m[2].split(".").pop(), repeated: m[1] === "repeated", annotations: annosFrom(lead) });
      lead = [];
    } else if (kind === "rpc") {
      const m = line.match(/^rpc\s+(\w+)\s*\(\s*([\w.]+)\s*\)\s*returns\s*\(\s*([\w.]+)\s*\)\s*;/);
      if (m) {
        const a = annosFrom(lead); const p = (a.http || "").split(/\s+/);
        items.push({ name: m[1], input: m[2].split(".").pop(), output: m[3].split(".").pop(),
          httpMethod: p[0] || "GET", httpPath: p[1] || "/", pathParams: [...(p[1] || "").matchAll(/\{(\w+)\}/g)].map((x) => x[1]) });
      }
      lead = [];
    }
  }
  return { items, next: i };
}

// ---------- model helpers ----------
const snake = (s) => s.replace(/(?<!^)([A-Z])/g, "_$1").toLowerCase();
const camel = (s) => s.charAt(0).toLowerCase() + s.slice(1);
const humanize = (s) => s.replace(/_unix$/, "").replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
const tsType = (f) => (SCALAR[f.type] || f.type) + (f.repeated ? "[]" : "");
const isMsg = (t) => /^[A-Z]/.test(t);

function fieldMeta(f) {
  const a = f.annotations;
  const isPk = "pk" in a, isTs = "timestamp" in a;
  // id/外部キー(`*_id`)は既定で secondary(タイトルにしない)。opaque な id が primary を奪う事故を防ぐ。
  const isId = isPk || /_id$/.test(f.name);
  const explicitRole = a.list; // @list primary|secondary|hidden(未指定は undefined)
  const listRole = explicitRole || (isId ? "secondary" : (f.type === "string" && !isTs ? "primary" : "secondary"));
  const widget = a.form || (isPk || isTs ? "readonly" : ("email" in a ? "email" : "text"));
  return { ...f, label: (a.label || humanize(f.name)).replace(/"/g, ""), ts: tsType(f),
    isPk, isTs, isId, explicitRole, isRequired: "required" in a, isEmail: "email" in a, isUnique: "unique" in a,
    isNumeric: ["int32", "int64", "double", "float"].includes(f.type),
    listRole, widget, editable: !(isPk || isTs) };
}

// primary(タイトル)は1つだけ選ぶ: @list primary の明示が最優先 → 既定 primary の先頭 → 先頭field。
// 明示アノテーションが field 順や型の既定に負けないようにする(summary が project_id に奪われる事故の修正)。
const pickPrimary = (metas) =>
  metas.find((m) => m.explicitRole === "primary")
  || metas.find((m) => m.listRole === "primary")
  || metas[0];
const displayCell = (m, ref) => m.isTs ? "{new Date(" + ref + "." + m.name + " * 1000).toLocaleDateString()}" : "{" + ref + "." + m.name + "}";

// ---------- templates ----------
function tplTypes(ent) {
  const L = [HEADER, "// entity 型\n", "export interface " + ent.name + " {"];
  for (const f of ent.fields) L.push("  " + f.name + ": " + (isMsg(f.type) ? f.type + (f.repeated ? "[]" : "") : tsType(f)) + ";");
  L.push("}\n");
  return L.join("\n");
}

function tplClient(ent, svc, msgByName) {
  const E = ent.name;
  const L = [HEADER, 'import { apiFetch } from "../../lib/api";', 'import type { ' + E + ' } from "../types/' + snake(E) + '";\n'];
  for (const r of svc.rpcs) {
    const fields = msgByName[r.input]?.fields || [];
    if (fields.some((f) => isMsg(f.type))) continue;
    const isBody = ["POST", "PUT", "PATCH"].includes(r.httpMethod);
    const args = [];
    for (const p of r.pathParams) args.push(p + ": string");
    const bodyFields = isBody ? fields.filter((f) => !r.pathParams.includes(f.name)) : [];
    const queryFields = !isBody ? fields.filter((f) => !r.pathParams.includes(f.name)) : [];
    if (bodyFields.length) args.push("body: { " + bodyFields.map((f) => f.name + ": " + tsType(f)).join("; ") + " }");
    for (const f of queryFields) args.push(f.name + "?: " + tsType(f));
    const rf = msgByName[r.output]?.fields || [];
    let ret = "void";
    if (rf.length === 1 && rf[0].type === E) ret = rf[0].repeated ? E + "[]" : E;
    let urlExpr = '"' + r.httpPath + '"';
    for (const p of r.pathParams) urlExpr = urlExpr.replace("{" + p + "}", '" + encodeURIComponent(' + p + ') + "');
    urlExpr = urlExpr.replace(/ \+ ""/g, "");
    const qs = queryFields.length
      ? "\n  const _qs = new URLSearchParams();" + queryFields.map((f) => "\n  if (" + f.name + " !== undefined) _qs.set(\"" + f.name + "\", String(" + f.name + "));").join("") + "\n  const _q = _qs.toString() ? \"?\" + _qs.toString() : \"\";"
      : "";
    const urlFinal = queryFields.length ? "(" + urlExpr + ") + _q" : urlExpr;
    const opts = ['method: "' + r.httpMethod + '"']; if (bodyFields.length) opts.push("body");
    L.push("export async function " + camel(r.name) + "(" + args.join(", ") + "): Promise<" + ret + "> {" + qs);
    L.push("  return apiFetch(" + urlFinal + ", { " + opts.join(", ") + " });");
    L.push("}\n");
  }
  return L.join("\n");
}

function tplList(ent) {
  const E = ent.name, s = snake(E);
  const metas = ent.fields.map(fieldMeta);
  const pk = metas.find((m) => m.isPk) || metas[0];
  const primary = pickPrimary(metas);
  const secondary = metas.filter((m) => m.listRole === "secondary" && m !== primary);
  const secondaryJsx = secondary.length
    ? " secondary={<>" + secondary.map((m) => displayCell(m, "r")).join(" <span> · </span> ") + "</>}"
    : "";
  const L = [HEADER, '"use client";', 'import { useEffect, useState } from "react";', 'import Link from "next/link";',
    'import { list' + E + 's } from "../../client/' + s + '";', 'import type { ' + E + ' } from "../../types/' + s + '";',
    'import { ListStack, ListRow, EmptyState } from "../../../lib/widgets";\n',
    "// 優先度カードリスト(全列テーブルにしない): primary を突出、secondary を従属。見た目は widget に委譲。",
    "export function " + E + "List() {",
    "  const [rows, setRows] = useState<" + E + "[]>([]);",
    "  useEffect(() => { list" + E + "s().then(setRows).catch(() => setRows([])); }, []);",
    "  if (rows.length === 0) {",
    '    return <EmptyState message="No ' + s + 's yet" action={<Link href="/' + s + 's/new">+ New</Link>} />;',
    "  }",
    "  return (",
    "    <ListStack>",
    "      {rows.map((r) => (",
    "        <ListRow key={r." + pk.name + "} href={`/" + s + "s/${r." + pk.name + "}`} primary={<>" + displayCell(primary, "r") + "</>}" + secondaryJsx + " />",
    "      ))}",
    "    </ListStack>",
    "  );",
    "}\n"];
  return L.join("\n");
}

function tplDetail(ent) {
  const E = ent.name, s = snake(E);
  const metas = ent.fields.map(fieldMeta);
  const pk = metas.find((m) => m.isPk) || metas[0];
  const primary = pickPrimary(metas);
  const rest = metas.filter((m) => m !== primary);
  const kvItems = rest.map((m) => '{ k: "' + m.label + '", v: <>' + displayCell(m, "item") + "</> }").join(", ");
  const L = [HEADER, '"use client";', 'import { useEffect, useState } from "react";', 'import Link from "next/link";',
    'import { get' + E + ' } from "../../client/' + s + '";', 'import { ' + E + 'DeleteButton } from "./' + E + 'DeleteButton";',
    'import type { ' + E + ' } from "../../types/' + s + '";',
    'import { KVList } from "../../../lib/widgets";\n',
    "// 詳細: 本質(primary)を先に、残りは従属表示(progressive disclosure)。見た目は widget に委譲。",
    "export function " + E + "Detail({ id }: { id: string }) {",
    "  const [item, setItem] = useState<" + E + " | null>(null);",
    "  useEffect(() => { get" + E + "(id).then(setItem).catch(() => setItem(null)); }, [id]);",
    '  if (!item) return <p style={{ color: "var(--text-faint)" }}>Loading…</p>;',
    "  return (",
    '    <div style={{ display: "grid", gap: "var(--sp-4)" }}>',
    '      <h2 style={{ margin: 0, fontSize: "var(--text-lg)" }}>' + displayCell(primary, "item") + "</h2>",
    "      <KVList items={[" + kvItems + "]} />",
    '      <div style={{ display: "flex", gap: "var(--sp-3)", alignItems: "center" }}>',
    '        <Link href={`/' + s + 's/${id}/edit`}>Edit</Link>',
    "        <" + E + "DeleteButton id={id} />",
    "      </div>", "    </div>", "  );", "}\n"];
  return L.join("\n");
}

function tplForm(ent) {
  const E = ent.name, s = snake(E);
  const editable = ent.fields.map(fieldMeta).filter((m) => m.editable);
  const L = [HEADER, '"use client";', 'import { useEffect, useState } from "react";', 'import { useRouter } from "next/navigation";',
    'import { create' + E + ', update' + E + ', get' + E + ' } from "../../client/' + s + '";',
    'import { Field, Button, ErrorText } from "../../../lib/widgets";\n',
    "// 生成フォーム(create/edit): 編集可能フィールドのみ。validation は @required/@email から生成(entity検証と同源)。",
    "export function " + E + "Form({ id }: { id?: string }) {",
    "  const router = useRouter();"];
  for (const m of editable) L.push("  const [" + m.name + ", set_" + m.name + '] = useState("");');
  L.push("  const [error, setError] = useState<string | null>(null);");
  L.push("  useEffect(() => {");
  L.push("    if (!id) return;");
  L.push("    get" + E + "(id).then((v) => {");
  for (const m of editable) L.push("      set_" + m.name + "(String(v." + m.name + " ?? \"\"));");
  L.push("    }).catch(() => {});");
  L.push("  }, [id]);");
  L.push("  async function submit(e: React.FormEvent) {");
  L.push("    e.preventDefault();");
  for (const m of editable) {
    if (m.isRequired || m.isEmail) L.push("    if (!" + m.name + '.trim()) { setError("' + m.label + ' is required"); return; }');
    if (m.isEmail) L.push("    if (!" + m.name + '.includes("@")) { setError("' + m.label + ' is invalid"); return; }');
  }
  L.push("    setError(null);");
  // 数値フィールドはフォーム state(string)から number へ変換して送る(int32/int64/double)
  L.push("    const body = { " + editable.map((m) => (m.isNumeric ? m.name + ": Number(" + m.name + ") || 0" : m.name)).join(", ") + " };");
  L.push("    if (id) await update" + E + "(id, body); else await create" + E + "(body);");
  L.push('    router.push("/' + s + 's");');
  L.push("    router.refresh();");
  L.push("  }");
  // 詳細/一覧画面と同じ質感に: カード内にフォームを置き、primary + cancel の2アクション。
  L.push("  return (");
  L.push('    <form onSubmit={submit} style={{ display: "grid", gap: "var(--sp-4)", maxWidth: 520, background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "var(--radius-md)", boxShadow: "var(--shadow-sm)", padding: "var(--sp-5)" }}>');
  for (const m of editable) L.push('      <Field label="' + m.label + '" type="' + m.widget + '" value={' + m.name + "} onChange={set_" + m.name + "} />");
  L.push("      {error && <ErrorText>{error}</ErrorText>}");
  L.push('      <div style={{ display: "flex", gap: "var(--sp-2)" }}>');
  L.push('        <Button type="submit" variant="primary">{id ? "Update" : "Create"}</Button>');
  L.push('        <Button variant="ghost" onClick={() => router.push("/' + s + 's")}>Cancel</Button>');
  L.push("      </div>");
  L.push("    </form>", "  );", "}\n");
  return L.join("\n");
}

function tplDelete(ent) {
  const E = ent.name, s = snake(E);
  return [HEADER, '"use client";', 'import { useRouter } from "next/navigation";', 'import { delete' + E + ' } from "../../client/' + s + '";',
    'import { Button } from "../../../lib/widgets";\n',
    "export function " + E + "DeleteButton({ id }: { id: string }) {",
    "  const router = useRouter();",
    "  async function onDelete() {",
    '    if (!confirm("Delete this ' + s + '?")) return;',
    "    await delete" + E + "(id);",
    '    router.push("/' + s + 's");',
    "    router.refresh();",
    "  }",
    '  return <Button variant="danger" onClick={onDelete}>Delete</Button>;',
    "}\n"].join("\n");
}

// pages (server components rendering client components) — レイアウト/見出しは Page widget に委譲
function pageList(E, s) {
  return [SCAFFOLD_HEADER, 'import Link from "next/link";',
    'import { ' + E + 'List } from "../../gen/ui/' + s + '/' + E + 'List";',
    'import { Page } from "../../lib/widgets";\n',
    "export default function " + E + "sPage() {",
    '  return (<Page title="' + E + 's" actions={<Link href="/' + s + 's/new">+ New</Link>}><' + E + 'List /></Page>);',
    "}\n"].join("\n");
}
function pageNew(E, s) {
  return [SCAFFOLD_HEADER, 'import { ' + E + 'Form } from "../../../gen/ui/' + s + '/' + E + 'Form";',
    'import { Page } from "../../../lib/widgets";\n',
    "export default function New" + E + "Page() {",
    '  return (<Page title="New ' + E + '"><' + E + 'Form /></Page>);',
    "}\n"].join("\n");
}
function pageDetail(E, s) {
  return [SCAFFOLD_HEADER, 'import { ' + E + 'Detail } from "../../../gen/ui/' + s + '/' + E + 'Detail";',
    'import { Page } from "../../../lib/widgets";\n',
    "export default function " + E + "DetailPage({ params }: { params: { id: string } }) {",
    '  return (<Page title="' + E + '"><' + E + 'Detail id={params.id} /></Page>);',
    "}\n"].join("\n");
}
function pageEdit(E, s) {
  return [SCAFFOLD_HEADER, 'import { ' + E + 'Form } from "../../../../gen/ui/' + s + '/' + E + 'Form";',
    'import { Page } from "../../../../lib/widgets";\n',
    "export default function Edit" + E + "Page({ params }: { params: { id: string } }) {",
    '  return (<Page title="Edit ' + E + '"><' + E + 'Form id={params.id} /></Page>);',
    "}\n"].join("\n");
}

// ---------- main ----------
function write(rel, content) {
  const dst = join(ROOT, rel);
  mkdirSync(dirname(dst), { recursive: true });
  writeFileSync(dst, content);
  console.log("gen:", rel);
}

// app/ ページは「アプリ所有の足場」: 既に存在すれば上書きしない(手書き画面を守る)。
function scaffold(rel, content) {
  const dst = join(ROOT, rel);
  if (existsSync(dst)) { console.log("keep:", rel); return; }
  mkdirSync(dirname(dst), { recursive: true });
  writeFileSync(dst, content);
  console.log("scaffold:", rel);
}

// proto はスタック直下 proto/ からの相対パスを argv で渡せる(省略時 user/v1/user.proto)。
// 新ドメインの scaffold 利用時は例: `npm run gen -- atlas/v1/atlas.proto`(REUSE.md)。
const protoRel = process.argv[2] ?? "proto/user/v1/user.proto";
const proto = readFileSync(join(ROOT, protoRel.startsWith("proto/") ? protoRel : "proto/" + protoRel), "utf8");
const model = parseProto(proto);
const msgByName = Object.fromEntries(model.messages.map((m) => [m.name, m]));
for (const svc of model.services) {
  const ent = model.messages.find((m) => "entity" in m.annotations && svc.name.replace(/Service$/, "") === m.name)
    || model.messages.find((m) => "entity" in m.annotations);
  const E = ent.name, s = snake(E);
  write("src/gen/types/" + s + ".ts", tplTypes(ent));
  write("src/gen/client/" + s + ".ts", tplClient(ent, svc, msgByName));
  write("src/gen/ui/" + s + "/" + E + "List.tsx", tplList(ent));
  write("src/gen/ui/" + s + "/" + E + "Detail.tsx", tplDetail(ent));
  write("src/gen/ui/" + s + "/" + E + "Form.tsx", tplForm(ent));
  write("src/gen/ui/" + s + "/" + E + "DeleteButton.tsx", tplDelete(ent));
  scaffold("src/app/" + s + "s/page.tsx", pageList(E, s));
  scaffold("src/app/" + s + "s/new/page.tsx", pageNew(E, s));
  scaffold("src/app/" + s + "s/[id]/page.tsx", pageDetail(E, s));
  scaffold("src/app/" + s + "s/[id]/edit/page.tsx", pageEdit(E, s));
}
